version: '3.8'
services:
  web:
    image: jepbura/bura-dev-web-ui:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # For gatsby develop
      - "8000:8000"
      # For gatsby serve
      - "9000:9000"
      # 9230, 9929: When start multiple instances of node app,
      #       first instance starts occupies 127.0.0.1:9229 and other instances cannot get to the port
      # see: https://dev.to/wataash/chrome-attach-debug-with-webstorm-328p
      # see: https://github.com/nodejs/node-inspect/issues/48#issuecomment-507889953
      - "9230:9230"
      - "9929:9929"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - CHOKIDAR_USEPOLLING=true